# Generated by Django 5.2.14 on 2026-05-12 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Canal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('tipo', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('facebook', 'Facebook Messenger'), ('tiktok', 'TikTok'), ('email', 'Email'), ('webhook', 'Webhook genérico')], default='whatsapp', max_length=20)),
                ('display_name', models.CharField(max_length=120)),
                ('phone_number_id', models.CharField(blank=True, help_text='WhatsApp Cloud API phone_number_id. Solo para tipo=whatsapp.', max_length=64)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['tipo', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wa_phone', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('empresa', models.CharField(blank=True, max_length=200)),
                ('tipo', models.CharField(choices=[('lead', 'Lead'), ('cliente', 'Cliente'), ('mayorista', 'Mayorista / empresa'), ('descartado', 'Descartado'), ('desconocido', 'No clasificado')], default='lead', max_length=20)),
                ('fuente', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('referido', 'Referido'), ('web', 'Sitio web'), ('directo', 'Directo / desconocido'), ('otro', 'Otro')], default='directo', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('fecha_primer_mensaje', models.DateTimeField(blank=True, null=True)),
                ('fecha_ultimo_mensaje', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-fecha_ultimo_mensaje'],
            },
        ),
        migrations.CreateModel(
            name='BandejaAgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre_display', models.CharField(blank=True, help_text='Sobrescribe `user.get_full_name()` en la UI de bandeja.', max_length=120)),
                ('wa_phone', models.CharField(blank=True, help_text='Número del agente para handover / coordinación interna.', max_length=20)),
                ('horario_inicio', models.TimeField(blank=True, null=True)),
                ('horario_fin', models.TimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True, help_text='Si False, el agente no recibe asignaciones automáticas.')),
                ('ultima_asignacion_at', models.DateTimeField(blank=True, help_text='Para round-robin justo: el agente con valor más antiguo recibe la siguiente conversación.', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bandeja_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direccion', models.CharField(choices=[('entrante', 'Entrante'), ('saliente', 'Saliente')], max_length=10)),
                ('tipo_contenido', models.CharField(choices=[('texto', 'Texto'), ('audio', 'Audio'), ('imagen', 'Imagen'), ('documento', 'Documento'), ('sticker', 'Sticker'), ('ubicacion', 'Ubicación'), ('otro', 'Otro')], default='texto', max_length=15)),
                ('contenido', models.TextField(blank=True)),
                ('wa_message_id', models.CharField(max_length=128, unique=True)),
                ('timestamp', models.DateTimeField()),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mensajes', to='bandeja.canal')),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='bandeja.contacto')),
                ('enviado_por', models.ForeignKey(blank=True, help_text='Usuario que envió el mensaje (solo direccion=saliente).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['contacto', '-timestamp'], name='bandeja_men_contact_91fed1_idx'), models.Index(fields=['direccion', '-timestamp'], name='bandeja_men_direcci_bd1d9e_idx')],
            },
        ),
    ]
