# Generated by Django 5.2.14 on 2026-05-12 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandeja', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversacionEtiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('nombre', models.CharField(max_length=80)),
                ('color', models.CharField(default='#94a3b8', help_text='Color hex para el chip, ej. #2563eb', max_length=7)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaGuardada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(help_text='Atajo. Ej: `medidas`, `precios-mayorista`.', max_length=40, unique=True)),
                ('titulo', models.CharField(max_length=120)),
                ('cuerpo', models.TextField()),
                ('activa', models.BooleanField(default=True)),
                ('usada_n_veces', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.AddField(
            model_name='mensaje',
            name='es_nota_privada',
            field=models.BooleanField(default=False, help_text='Si True, el mensaje no se envía al cliente — solo visible para agentes.'),
        ),
        migrations.CreateModel(
            name='ContactoEtiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etiquetas_rel', to='bandeja.contacto')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('pendiente', 'Pendiente'), ('pospuesta', 'Pospuesta'), ('resuelta', 'Resuelta')], default='abierta', max_length=20)),
                ('pospuesta_hasta', models.DateTimeField(blank=True, null=True)),
                ('primera_respuesta_at', models.DateTimeField(blank=True, help_text='Timestamp del primer mensaje saliente del agente. Para SLA.', null=True)),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultimo_mensaje', models.DateTimeField(blank=True, null=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('objeto_id', models.PositiveIntegerField(blank=True, null=True)),
                ('asesor_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversaciones_asignadas', to=settings.AUTH_USER_MODEL)),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversaciones', to='bandeja.canal')),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones', to='bandeja.contacto')),
                ('objeto_ct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-fecha_ultimo_mensaje', '-fecha_apertura'],
            },
        ),
        migrations.AddField(
            model_name='mensaje',
            name='conversacion',
            field=models.ForeignKey(blank=True, help_text='Conversación a la que pertenece. Nullable durante migraciones.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes', to='bandeja.conversacion'),
        ),
        migrations.AddIndex(
            model_name='mensaje',
            index=models.Index(fields=['conversacion', '-timestamp'], name='bandeja_men_convers_07a850_idx'),
        ),
        migrations.AddField(
            model_name='conversacionetiqueta',
            name='conversacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etiquetas_rel', to='bandeja.conversacion'),
        ),
        migrations.AddField(
            model_name='conversacionetiqueta',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversacionetiqueta',
            name='etiqueta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bandeja.etiqueta'),
        ),
        migrations.AddField(
            model_name='contactoetiqueta',
            name='etiqueta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bandeja.etiqueta'),
        ),
        migrations.AddField(
            model_name='respuestaguardada',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas_guardadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='conversacion',
            index=models.Index(fields=['estado', '-fecha_ultimo_mensaje'], name='bandeja_con_estado_7f1bd5_idx'),
        ),
        migrations.AddIndex(
            model_name='conversacion',
            index=models.Index(fields=['asesor_asignado', 'estado'], name='bandeja_con_asesor__c4767b_idx'),
        ),
        migrations.AddIndex(
            model_name='conversacion',
            index=models.Index(fields=['objeto_ct', 'objeto_id'], name='bandeja_con_objeto__066156_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conversacionetiqueta',
            unique_together={('conversacion', 'etiqueta')},
        ),
        migrations.AlterUniqueTogether(
            name='contactoetiqueta',
            unique_together={('contacto', 'etiqueta')},
        ),
    ]
