# Generated by Django 5.2.14 on 2026-05-12 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandeja', '0004_macro_ejecucionmacro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='fusionado_en',
            field=models.ForeignKey(blank=True, help_text='Contacto destino si éste fue fusionado.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fusionados', to='bandeja.contacto'),
        ),
        migrations.CreateModel(
            name='BitacoraContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=40)),
                ('detalle', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitacora', to='bandeja.contacto')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EncuestaCSAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enviada_at', models.DateTimeField(blank=True, null=True)),
                ('puntaje', models.PositiveSmallIntegerField(blank=True, help_text='1-5. None = pendiente de respuesta.', null=True)),
                ('comentario', models.TextField(blank=True)),
                ('respondida_at', models.DateTimeField(blank=True, null=True)),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csats', to='bandeja.contacto')),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csats', to='bandeja.conversacion')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['conversacion', '-created_at'], name='bandeja_enc_convers_3a0d32_idx'), models.Index(fields=['puntaje', '-respondida_at'], name='bandeja_enc_puntaje_e7bed0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Mencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('leida_at', models.DateTimeField(blank=True, null=True)),
                ('mencionado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menciones_recibidas', to=settings.AUTH_USER_MODEL)),
                ('mensaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menciones', to='bandeja.mensaje')),
            ],
            options={
                'ordering': ['-creado_at'],
                'unique_together': {('mensaje', 'mencionado')},
            },
        ),
    ]
